### ISSUE TITLE
KeyError: 'Worksheet Historique par jour does not exist.'

### ISSUE THREAD

**Issue by pbranly** [ssenart/PyGazpar#17]
An error occured while querying PyGazpar library : %s Traceback (most recent call last):
  File "/home/PyGazpar/venv/lib/python3.8/site-packages/pygazpar/__main__.py", line 86, in main
    client.update()
  File "/home/PyGazpar/venv/lib/python3.8/site-packages/pygazpar/client.py", line 118, in update
    self.__updateLiveMode()
  File "/home/PyGazpar/venv/lib/python3.8/site-packages/pygazpar/client.py", line 239, in __updateLiveMode
    self.__data = DataFileParser.parse(filename, self.__meterReadingFrequency, self.__lastNRows)
  File "/home/PyGazpar/venv/lib/python3.8/site-packages/pygazpar/datafileparser.py", line 37, in parse
    worksheet = workbook[worksheetNameByFrequency[dataReadingFrequency]]
  File "/home/PyGazpar/venv/lib/python3.8/site-packages/openpyxl/workbook/workbook.py", line 290, in __getitem__
    raise KeyError("Worksheet {0} does not exist.".format(key))
KeyError: 'Worksheet Historique par jour does not exist.'

**Comment by pbranly** [comment]
erreur disparue
