### ISSUE TITLE
KeyError("Worksheet {0} does not exist.".format(key)) KeyError: 'Worksheet Historique par jour does not exist.'

### ISSUE THREAD

**Issue by kalon33** [ssenart/PyGazpar#2]
First, thanks for your very useful script to provide data for home automation.

When launching a script using pygazpar from 2020-05-29, I got this error:
```
/usr/local/lib/python2.7/dist-packages/openpyxl/styles/stylesheet.py:214: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
Traceback (most recent call last):
  File "./test_json.py", line 17, in <module>
    client.update()
  File "/usr/local/lib/python2.7/dist-packages/pygazpar/client.py", line 127, in update
    ws = wb['Historique par jour']
  File "/usr/local/lib/python2.7/dist-packages/openpyxl/workbook/workbook.py", line 290, in __getitem__
    raise KeyError("Worksheet {0} does not exist.".format(key))
KeyError: 'Worksheet Historique par jour does not exist.'

```
Could it be possible to provide a fix for this? Thanks :)

**Comment by ssenart** [comment]
Sure, which version are you using ? 

This behaviour is similar to a bug I have fixed in version 0.1.10.

**Comment by kalon33** [comment]
Initially the latest available through pip, but I also tested with latest git master before reporting, triggering the exact error I sent here.

**Comment by ssenart** [comment]
Indeed, I have managed to reproduce it from my desktop.

I have brought a fix in version 0.1.11. It came from a waiting time too short.

Could you confirm it fixes on your side as well ?

Thanks

**Comment by kalon33** [comment]
Yep, it seems to fix that one, but raises another bug unfortunately:

```
Traceback (most recent call last):
  File "test_json.py", line 17, in <module>
    client.update()
  File "/usr/local/lib/python2.7/dist-packages/pygazpar/client.py", line 113, in update
    download_button_element = driver.find_element_by_xpath("//button[@id='_eConsoconsoDetaille_WAR_eConsoportlet_:idFormConsoDetaille:telechargerDonnees']/span")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@id='_eConsoconsoDetaille_WAR_eConsoportlet_:idFormConsoDetaille:telechargerDonnees']/span
```

**Comment by kalon33** [comment]
Tried another time, and this time, triggers this one again:
```
/usr/local/lib/python2.7/dist-packages/openpyxl/styles/stylesheet.py:214: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
Traceback (most recent call last):
  File "test_json.py", line 17, in <module>
    client.update()
  File "/usr/local/lib/python2.7/dist-packages/pygazpar/client.py", line 127, in update
    ws = wb['Historique par jour']
  File "/usr/local/lib/python2.7/dist-packages/openpyxl/workbook/workbook.py", line 290, in __getitem__
    raise KeyError("Worksheet {0} does not exist.".format(key))
KeyError: 'Worksheet Historique par jour does not exist.'
```

**Comment by ssenart** [comment]
Still some timing issue... I really have to harden this part...

However, i've just realized that you are using python2 instead of python3.

Could you retry with python3 and tell me.

In the meantime, I try to find a way to get around those timing issues.

**Comment by kalon33** [comment]
```
Traceback (most recent call last):
  File "test_json.py", line 17, in <module>
    client.update()
  File "/usr/local/lib/python3.6/dist-packages/pygazpar/client.py", line 113, in update
    download_button_element = driver.find_element_by_xpath("//button[@id='_eConsoconsoDetaille_WAR_eConsoportlet_:idFormConsoDetaille:telechargerDonnees']/span")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@id='_eConsoconsoDetaille_WAR_eConsoportlet_:idFormConsoDetaille:telechargerDonnees']/span

```

**Comment by kalon33** [comment]
Last git master from a few minutes ago, I still got the problem, unfortunately:

```
Traceback (most recent call last):
  File "test_json.py", line 17, in <module>
    client.update()
  File "/usr/local/lib/python3.6/dist-packages/pygazpar/client.py", line 113, in update
    download_button_element = driver.find_element_by_xpath("//button[@id='_eConsoconsoDetaille_WAR_eConsoportlet_:idFormConsoDetaille:telechargerDonnees']/span")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@id='_eConsoconsoDetaille_WAR_eConsoportlet_:idFormConsoDetaille:telechargerDonnees']/span
```

**Comment by ssenart** [comment]
Sorry for that, I have brought few changes in version 0.1.13. Try tuning the waiting time parameter starting with value = 30 seconds. If it still fails with such messages, try to increase the value. Let me know the results.

**Comment by kalon33** [comment]
I had a timeout, so I raised to 60s and got this error, sorry :(

```
Traceback (most recent call last):
  File "test_json.py", line 17, in <module>
    client.update()
  File "/usr/local/lib/python3.6/dist-packages/pygazpar/client.py", line 69, in update
    email_element = driver.find_element_by_id("_EspacePerso_WAR_EPportlet_:seConnecterForm:email")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="_EspacePerso_WAR_EPportlet_:seConnecterForm:email"]
```

**Comment by ssenart** [comment]
This means that it does not find email textbox on the GrDF login page: it is weird.

1) Try to login and download the Excel file manually (Jour radio button in Consommation tab) with the Firefox installed on the same machine. Open the Excel file and confirm you see one line per observation day : that's this file the program download and parse.

2) Could you give the source code of your test program : test_json.py

3) Also try the command line : 

`python -m pygazpar -u <your username> -p <your password> -t /tmp -s 30 -w /path/to/geckodriver`

On my desktop, it works 100% with the last version.

**Comment by kalon33** [comment]
May it be linked to the fact that I have no gaz consumption for a month or so? I can access to data on GRDF website, but no one line per observation day: it "stops" on the 2020-06-01.
![Capture d’écran de 2020-07-01 10-32-17](https://user-images.githubusercontent.com/460731/86222193-322c5780-bb86-11ea-8fa3-28784cd3b7d1.png)

**Comment by ssenart** [comment]
What about the downloaded Excel file ? Do you have a copy of it ? (Button Télécharger)

Take care to remove any personal data before posting it !

**Comment by kalon33** [comment]
> What about the downloaded Excel file ? Do you have a copy of it ? (Button Télécharger)
> 
> Take care to remove any personal data before posting it !

You mean this file ? 
[Consommations gaz_Maison_01012020_01072020.xlsx](https://github.com/ssenart/PyGazpar/files/4856747/Consommations.gaz_Maison_01012020_01072020.xlsx)

**Comment by ssenart** [comment]
Your file format is fine. Data inside are fine as well.

What is the actual error message you have currently (this morning) ?

**Comment by kalon33** [comment]
Just got this one:
```
Traceback (most recent call last):
  File "test_json.py", line 17, in <module>
    client.update()
  File "/usr/local/lib/python3.6/dist-packages/pygazpar/client.py", line 113, in update
    download_button_element = driver.find_element_by_xpath("//button[@id='_eConsoconsoDetaille_WAR_eConsoportlet_:idFormConsoDetaille:telechargerDonnees']/span")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //button[@id='_eConsoconsoDetaille_WAR_eConsoportlet_:idFormConsoDetaille:telechargerDonnees']/span

```

**Comment by ssenart** [comment]
Ok, this means that your are not using the last version 0.1.13.

Could you double check that : you should have in client.py, line 108 :

            download_button_element = driver.find_element_by_xpath("//button[@onclick=\"envoieGATelechargerConsoDetaille('particulier', 'jour_kwh');\"]/span")

Your message displays the xpath with the old way of identifying the Download button.

**Comment by kalon33** [comment]
Ok, so I removed all existing versions of PyGazpar from my machine, and installed it from scratch. Sorry, I didn't noticed it wasn't using the correct version even if it was installed. There, I got this error:

```
An error occured while querying PyGazpar library : %s Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pygazpar-0.1.13-py3.6.egg/pygazpar/__main__.py", line 35, in main
    client.update()
  File "/usr/local/lib/python3.6/dist-packages/pygazpar-0.1.13-py3.6.egg/pygazpar/client.py", line 104, in update
    daily_consumption_element = driver.find_element_by_xpath("//table[@id='_eConsoconsoDetaille_WAR_eConsoportlet_:idFormConsoDetaille:panelTypeGranularite1']/tbody/tr/td[3]/label")
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //table[@id='_eConsoconsoDetaille_WAR_eConsoportlet_:idFormConsoDetaille:panelTypeGranularite1']/tbody/tr/td[3]/label
```

**Comment by ssenart** [comment]
At the time you got this error, did you connect the web site and be able to display the "Consommation" page normally.

This error says that the "Jour" radio button cannot be found in this page.

Please, could you retry and ensure the site is working well before.

Let me know...

**Comment by kalon33** [comment]
Ok, so the error is true, I couldn't find a download button in "jour" display from the "consommation" page on GRDF website. Maybe because I didn't use gaz for a few months
