### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by nicolas-r** [ssenart/PyGazpar#38]
Hello

I'm trying to use your module and I get the following error

An unexpected error occured while updating the data
Traceback (most recent call last):
  File "D:\Logiciels\Python\Python39\lib\site-packages\pygazpar\client.py", line 115, in __updateLiveMode
    self.__downloadFile(session, downloadUrl, self.__tmpDirectory)
  File "D:\Logiciels\Python\Python39\lib\site-packages\pygazpar\client.py", line 155, in __downloadFile
    response.raise_for_status()
  File "D:\Logiciels\Python\Python39\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://monespace.grdf.fr/api/e-conso/pce/consommation/informatives/telecharger?frequence=Journalier&dateDebut=2021-12-09&dateFin=2021-12-19&pceList%5B%5D=your%20PCE%20identifier
Traceback (most recent call last):
  File "C:\Users\nicol\Documents\dev\grdf\grdf-import.py", line 12, in <module>
    client.update()
  File "D:\Logiciels\Python\Python39\lib\site-packages\pygazpar\client.py", line 57, in update
    self.__updateLiveMode()
  File "D:\Logiciels\Python\Python39\lib\site-packages\pygazpar\client.py", line 115, in __updateLiveMode
    self.__downloadFile(session, downloadUrl, self.__tmpDirectory)
  File "D:\Logiciels\Python\Python39\lib\site-packages\pygazpar\client.py", line 155, in __downloadFile
    response.raise_for_status()
  File "D:\Logiciels\Python\Python39\lib\site-packages\requests\models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://monespace.grdf.fr/api/e-conso/pce/consommation/informatives/telecharger?frequence=Journalier&dateDebut=2021-12-09&dateFin=2021-12-19&pceList%5B%5D=your%20PCE%20identifier

Nicolas

**Comment by nicolas-r** [comment]
In fact, i just foudn that I have missed updated the PCE identifier...
