### ISSUE TITLE
Fix an error when no temperature data is available

### ISSUE THREAD

**Issue by ssenart** [ssenart/PyGazpar#75]
The following error may occur when no temperature data is available:

```python
2024-12-21 12:40:35 WARNING [root] Error while fetching data from GrDF: Traceback (most recent call last):
  File "c:\Users\steph\Qsync\Workspace\Python\gazpar2haws\gazpar2haws\gazpar.py", line 64, in publish
    data = client.loadSince(pceIdentifier=self._pce_identifier, lastNDays=last_days, frequencies=[pygazpar.Frequency.DAILY])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\steph\Qsync\Workspace\Python\gazpar2haws\.venv\Lib\site-packages\pygazpar\client.py", line 39, in loadSince
    res = self.loadDateRange(pceIdentifier, startDate, endDate, frequencies)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\steph\Qsync\Workspace\Python\gazpar2haws\.venv\Lib\site-packages\pygazpar\client.py", line 52, in loadDateRange
    res = self.__dataSource.load(pceIdentifier, startDate, endDate, frequencies)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\steph\Qsync\Workspace\Python\gazpar2haws\.venv\Lib\site-packages\pygazpar\datasource.py", line 64, in load
    res = self._loadFromSession(auth_token, pceIdentifier, startDate, endDate, frequencies)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\steph\Qsync\Workspace\Python\gazpar2haws\.venv\Lib\site-packages\pygazpar\datasource.py", line 327, in _loadFromSession
    daily = JsonParser.parse(data, temperatures, pceIdentifier)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\steph\Qsync\Workspace\Python\gazpar2haws\.venv\Lib\site-packages\pygazpar\jsonparser.py", line 33, in parse
    temperature = temperatures.get(releve['journeeGaziere'])
                  ^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'
```

**Comment by ssenart** [comment]
Fixed with version [1.2.5](https://github.com/ssenart/PyGazpar/releases/tag/1.2.5)
